# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: configure build
        run: cl /EHsc main.cpp fraction.cpp
      
      - name: 'art'
        uses: actions/upload-artifact@v2
        with:
            name: new-artifact
            path: main.exe
            retention-days: 5
            
  Telegram:
    runs-on: ubuntu-latest 
    needs: build
    steps:
     - uses: actions/checkout@master
     - name: send mes
       uses: appleboy/telegram-action@master
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: send art

     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         name: new-artifact



   #  - name: send mes
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ secrets.TELEGRAM_TO_DEBUG }}
       #  token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
      #   document: main.exe
